name: Update Prod Draft Release

on:
  push:
    branches:
      - preprod
jobs:
  create-or-replace-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.8' # Ensure compatibility

      - name: Install GitHub CLI
        run: |
          curl -L https://github.com/cli/cli/releases/download/v1.9.2/gh_1.9.2_linux_amd64.deb -o ghcli.deb
          sudo dpkg -i ghcli.deb

      - name: Login to GitHub CLI
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Check for existing draft release that starts with 'prod-'
        run: |
          DRAFT_RELEASE_ID=$(gh api repos/${{ github.repository }}/releases --jq '.[] | select( (.draft==true) and (.tag_name | startswith("prod-")) ) | .tag_name' | head -n 1)

          if [ -n "$DRAFT_RELEASE_ID" ]; then
            gh release delete $DRAFT_RELEASE_ID -y
          fi

          RELEASE_TAG="prod-$(date +%Y%m%d%H%M%S)"
          gh release create "$RELEASE_TAG" --draft --title "Prod Draft Release $RELEASE_TAG" --notes "Release notes for $RELEASE_TAG"
